# Generated by Django 4.2.4 on 2023-09-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCurrencyType',
        ),
    ]
